name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {os: windows-latest, framework: net461, runtime: win-x64}
          # - {os: ubuntu-latest, framework: net7.0, runtime: linux-x64}
        build_type:
          - {
            name: 'Build',
            configuration: Debug,
            command: 'dotnet build ConsoleApp',
          }
          - {
            name: 'Build',
            configuration: Release,
            command: 'dotnet build ConsoleApp',
          }
          - {
            name: 'Run tests',
            configuration: Release,
            command: 'dotnet test --logger "console;verbosity=detailed"',
          }

    runs-on: ${{ matrix.platform.os }}
    name: ${{ matrix.build_type.name }} (${{ matrix.build_type.configuration }}, ${{ matrix.platform.os }}

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: ${{ matrix.build_type.name }}
      run: >
        ${{ matrix.build_type.command }}
        --framework=${{ matrix.platform.framework }}
        --runtime=${{ matrix.platform.runtime }}
        --configuration=${{ matrix.build_type.configuration }}
