name: Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build Debug
      run: msbuild ConsoleApp\ConsoleApp.csproj -target:Rebuild -property:Configuration=Debug -restore
    - name: Build Release
      run: msbuild ConsoleApp\ConsoleApp.csproj -target:Rebuild -property:Configuration=Release -restore
    - name: Publish to single executable
      run: msbuild ConsoleApp\ConsoleApp.csproj -target:Rebuild /p:DeployOnBuild=true /p:PublishProfile=publish-single-file -restore
    - name: Test
      run: dotnet test --logger "console;verbosity=detailed" --configuration Release
